# Generated by Django 5.2 on 2025-04-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
