# Generated by Django 5.2 on 2025-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactmessage_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
